### ISSUE TITLE
App should have option for showing popup/map highlight.

### ISSUE THREAD

**Issue by gavinr** [Esri/storymap-journal#31]
It looks like on [this line](https://github.com/Esri/map-journal-storytelling-template-js/blob/master/src/app/storymaps/tpl/ui/MainStage.js#L371) the [highlight](https://developers.arcgis.com/javascript/jsapi/popup-amd.html#highlight) functionality of the Popup is being disabled across the entire app. It would be nice if we could enable this (default behavior) via an app setting.

**Comment by glazou** [comment]
We disabled the highlight has the crosshair symbol that was used was not looking good in many case. I just noticed that this this is now a regular rectangle so I think we can re-enable this or make it an option. Stay tuned.

**Comment by gavinr** [comment]
Thanks!
