### ISSUE TITLE
No axis labels for graphs in map pop-ups

### ISSUE THREAD

**Issue by pleavin** [Esri/storymap-journal#78]
There seems to be no way to label the axis on graphs that are created in the pop-ups. Furthermore, the y-axis just has no labels at all. Am I just not seeing the options to change this? This may be more of a holistic issue than one directed at this repo.

![y-axis](https://cloud.githubusercontent.com/assets/12074592/25923997/ad3ea576-359d-11e7-8199-96c603d3a7b6.PNG)

**Comment by oevans** [comment]
Yes, enhancement requests for the pop-ups should be directed toward [ArcGIS Ideas](https://geonet.esri.com/community/arcgis-ideas/) or [Esri Support](https://support.esri.com).
